# Generated by Django 5.2.3 on 2025-06-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="cliente",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="factura",
            name="nombre",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
