# Generated by Django 5.2.3 on 2025-06-18 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0002_alter_factura_cliente_alter_factura_nombre"),
        ("inventario", "0003_alter_libro_precio_alter_libro_pvp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lineafactura",
            options={
                "ordering": ["id"],
                "verbose_name": "Línea de Factura",
                "verbose_name_plural": "Líneas de Factura",
            },
        ),
        migrations.AddField(
            model_name="factura",
            name="created_by",
            field=models.ForeignKey(
                help_text="Usuario que creó la factura",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="facturas_creadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="fecha_anulacion",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que se anuló la factura",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="gastos_envio",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Gastos de envío",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="motivo_anulacion",
            field=models.TextField(
                blank=True, help_text="Motivo por el que se anuló la factura", null=True
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="numero_borrador",
            field=models.CharField(
                blank=True,
                help_text="Número temporal para borradores",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="base_iva",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Base imponible antes de IVA",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="cliente",
            field=models.CharField(
                blank=True, help_text="Nombre del cliente", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="cp_ciudad",
            field=models.CharField(
                blank=True,
                help_text="Código postal y ciudad",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Fecha y hora de creación"
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="descuento",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Descuento general aplicado a la factura (%)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="domicilio",
            field=models.CharField(
                blank=True,
                help_text="Dirección de facturación",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="estado",
            field=models.CharField(
                choices=[
                    ("borrador", "Borrador"),
                    ("emitida", "Emitida"),
                    ("pagada", "Pagada"),
                    ("anulada", "Anulada"),
                ],
                default="borrador",
                help_text="Estado actual de la factura",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="fecha",
            field=models.DateField(help_text="Fecha de emisión de la factura"),
        ),
        migrations.AlterField(
            model_name="factura",
            name="fecha_pago",
            field=models.DateField(
                blank=True, help_text="Fecha en que se realizó el pago", null=True
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="iva",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=21.0,
                help_text="Porcentaje de IVA aplicado",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="nif",
            field=models.CharField(
                blank=True, help_text="NIF/CIF del cliente", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="nombre",
            field=models.CharField(
                blank=True,
                help_text="Nombre comercial o de facturación",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="notas",
            field=models.TextField(
                blank=True, help_text="Notas o comentarios adicionales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="numero",
            field=models.CharField(
                blank=True,
                help_text="Número oficial de factura",
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="recargo_equivalencia",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Porcentaje de recargo de equivalencia",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="telefono",
            field=models.CharField(
                blank=True, help_text="Teléfono de contacto", max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Importe total de la factura",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="updated_on",
            field=models.DateTimeField(
                auto_now=True, help_text="Fecha y hora de última modificación"
            ),
        ),
        migrations.AlterField(
            model_name="lineafactura",
            name="cantidad",
            field=models.IntegerField(help_text="Cantidad de libros"),
        ),
        migrations.AlterField(
            model_name="lineafactura",
            name="descuento",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Descuento aplicado a esta línea (%)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lineafactura",
            name="factura",
            field=models.ForeignKey(
                help_text="Factura a la que pertenece esta línea",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lineas",
                to="facturacion.factura",
            ),
        ),
        migrations.AlterField(
            model_name="lineafactura",
            name="importe",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Importe total de la línea",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lineafactura",
            name="libro",
            field=models.ForeignKey(
                help_text="Libro vendido",
                on_delete=django.db.models.deletion.PROTECT,
                to="inventario.libro",
            ),
        ),
        migrations.AlterField(
            model_name="lineafactura",
            name="precio",
            field=models.DecimalField(
                decimal_places=2, help_text="Precio unitario", max_digits=10
            ),
        ),
    ]
