# Generated by Django 5.2.3 on 2025-06-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0003_alter_lineafactura_options_factura_created_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("direccion", models.CharField(max_length=255)),
                ("nif", models.CharField(max_length=255)),
                ("gif", models.CharField(max_length=255)),
                ("iban", models.CharField(max_length=255)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
    ]
