# Generated by Django 5.2.3 on 2025-06-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("pvp", models.DecimalField(decimal_places=2, max_digits=10)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cantidad", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Libro",
                "verbose_name_plural": "Libros",
            },
        ),
    ]
