# Generated by Django 5.2.3 on 2025-06-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_libro_descuento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="libro",
            name="pvp",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
